# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    # Download the requirements file from the other repo before installing dependencies
    # https://raw.githubusercontent.com/USERNAME/REPO_NAME/main/requirements.txt
    pre_install:
      # 1. Download the external requirements file
      # https://raw.githubusercontent.com/scikit-plots/scikit-plots/main/requirements/all.txt
      - curl -sSL https://raw.githubusercontent.com/scikit-plots/scikit-plots/main/requirements/doc.txt -o requirements.txt
      # 2. Delete the line containing '-r core.txt'
      - sed -i '/-r core.txt/d' requirements.txt

# Build documentation in the "docs/" directory with Sphinx
# Change to docs/conf.py if your conf.py is inside a docs folder
sphinx:
  configuration: ./conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: requirements.txt
