# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    # Download the requirements file from the other repo before installing dependencies
    # https://raw.githubusercontent.com/USERNAME/REPO_NAME/main/requirements.txt
    pre_install:
      # 1. Download the external requirements file
      # https://raw.githubusercontent.com/scikit-plots/scikit-plots/main/requirements/all.txt
      - curl -sSL https://raw.githubusercontent.com/scikit-plots/scikit-plots/main/requirements/doc.txt -o requirements.txt
      # 2. Delete the line referencing core.txt (quoted YAML string)
      - sed -i '/core.txt/d' requirements.txt
      # 3. Append additional documentation packages
      # - echo "sphinx-issues" >> requirements.txt
      # - printf "sphinx\nsphinx-rtd-theme\nsphinx-issues\n" >> requirements.txt
      # 3. Append multiple lines at once
      - |
        cat << 'EOF' >> requirements.txt
        scikit-plots
        sphinx
        sphinx-rtd-theme
        sphinx-issues
        EOF

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: requirements.txt
