# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Scikit-plots learn'
author = 'scikit-plots community'
copyright = '2024, scikit-plots community (BSD-3 Clause License)'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.extlinks",  # Markup to shorten external links by extlinks
    'sphinx.ext.intersphinx',  # Link to other projects’ documentation
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',  # Add links to highlighted source code
    'sphinx_issues',
    "sphinx_tags",  # Needs to be loaded *after* autodoc.
    "sphinx_tabs.tabs",  # Tabbed content extension
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

default_role = 'literal'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'sphinx_rtd_theme'
# html_theme = "furo"
html_theme = "pydata_sphinx_theme"  # scikit-learn like

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Scikit-plotslearn'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Scikit-plotslearn.tex', 'Scikit-plots Learn Documentation',
     'scikit-plots community', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'scikit-plotslearn', 'Scikit-plots Learn Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'scikit-plotslearn', 'Scikit-plots Learn Documentation',
     author, 'scikit-plotslearn', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    "scikitplot": ("https://scikit-plots.github.io/dev/", (None, "https://scikit-plots.github.io/stable/")),
    # Build
    "python": (f"https://docs.python.org/{sys.version_info.major}/", None),
    "pip": ("https://pip.pypa.io/en/stable/", None),
    "meson-python": ("https://mesonbuild.com/meson-python/", None),
    "setuptools": ("https://setuptools.pypa.io/en/stable/", None),
    "packaging": ("https://packaging.python.org/en/latest/", None),
    "virtualenv": ("https://virtualenv.pypa.io/en/stable/", None),
    "IPython": ("https://ipython.readthedocs.io/en/stable/", None),
    "ipykernel": ("https://ipykernel.readthedocs.io/en/latest/", None),
    # Test
    "pytest": ("https://pytest.org/en/stable/", None),
    "tox": ("https://tox.wiki/en/stable/", None),
    # Docs
    'sphinx': ("https://www.sphinx-doc.org/en/master/", None),
    "pst": ("https://pydata-sphinx-theme.readthedocs.io/en/latest/", None),
    "numpydoc": ("https://numpydoc.readthedocs.io/en/latest/", None),
    # Data Manuplation
    "numpy": ("https://numpy.org/devdocs/", (None, "https://numpy.org/doc/stable/")),
    "scipy": ("https://scipy.github.io/devdocs/", (None, "https://docs.scipy.org/doc/scipy/")),
    "pandas": ("https://pandas.pydata.org/docs/dev/", (None, "https://pandas.pydata.org/pandas-docs/stable/")),
    # Visualization
    "cycler": ("https://matplotlib.org/cycler/", None),
    "matplotlib": ("https://matplotlib.org/devdocs/", (None, "https://matplotlib.org/stable/")),
    "astropy": ("https://docs.astropy.org/en/latest/", (None, "https://docs.astropy.org/en/stable/")),
    "seaborn": ("https://seaborn.pydata.org/", None),
    # ML
    "sklearn": ("https://scikit-learn.org/dev/", (None, "https://scikit-learn.org/stable/")),
    "statsmodels": ("https://www.statsmodels.org/stable/", None),
    # DL
    # 'keras': ('https://keras.io/api/', None),  # Add Keras API documentation
    "tensorflow": (
        "https://www.tensorflow.org/api_docs/python/",
        (
            None,
            "https://github.com/celik-muhammed/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
            "https://github.com/GPflow/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
            "https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tf2_py_objects.inv",
        ),
    ),
    "tensorflow_probability": (
        "https://www.tensorflow.org/probability/api_docs/python/",
        (
            None,
            "https://github.com/celik-muhammed/tensorflow-intersphinx/raw/master/tfp_py_objects.inv",
            "https://github.com/GPflow/tensorflow-intersphinx/raw/master/tfp_py_objects.inv",
            "https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tfp_py_objects.inv",
        ),
    ),
    "pytorch": (
        "https://pytorch.org/docs/stable/",
        (
            None,
            "https://github.com/pytorch/docs/raw/main/stable/objects.inv",
        ),
    ),
    "transformers": ("https://huggingface.co/docs/transformers/main/en/", None),
    "datasets": ("https://huggingface.co/docs/datasets/main/en/", None),
    # image
    "aggdraw": ("https://aggdraw.readthedocs.io/en/stable/", None),
    "pillow": ("https://pillow.readthedocs.io/en/stable/", None),
    "imageio": ("https://imageio.readthedocs.io/en/stable/", None),
    "skimage": ("https://scikit-image.org/docs/stable/", None),
    # Misc
    "joblib": ("https://joblib.readthedocs.io/en/latest/", None),
    "dateutil": ("https://dateutil.readthedocs.io/en/stable/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "skops": ("https://skops.readthedocs.io/en/stable/", None),
    "pluggy": ("https://pluggy.readthedocs.io/en/stable/", None),
    "flask": ("https://flask.palletsprojects.com/en/stable/", None),
}

# -- Sphinx-Issues configuration --

issues_github_path = "scikit-plots/scikit-plots"
