# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('.'))

# https://github.com/scikit-plots/scikit-plots
# from . import _sphinx_ai_assistant  # dev

# -- Project information -----------------------------------------------------

project = 'Scikit-plots Learn'
author = 'scikit-plots community'
copyright = '2024, scikit-plots community (BSD-3 Clause License)'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''

_full_version = release or version or "dev"

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # Built-in extensions (load early)
    "sphinx.ext.ifconfig",  # Include content based on configuration
    "sphinx.ext.extlinks",  # Markup to shorten external links by extlinks
    "sphinx.ext.intersphinx",  # Link to other projects’ documentation
    # "sphinx.ext.linkcode",  # Add external links to source code 'sphinx.ext.linkcode', 'numpydoc.linkcode'
    'sphinx.ext.mathjax',  # Render mathematical expressions using MathJax.
    'sphinx.ext.viewcode',  # Add links to highlighted source code
    # Third-party extensions (load after built-ins and matplotlib/IPython)
    "sphinx_design",  # Add design components and elements to documentation. Add directive type "dropdown" "grid"
    'sphinx_issues',
    "sphinx_tabs.tabs",  # Tabbed content extension
    "sphinx_tags",  # Needs to be loaded *after* autodoc.
    # "scikitplot._externals._sphinx_ext._sphinxcontrib_youtube",
    # "scikitplot._externals._sphinx_ext._sphinx_ai_assistant",
    "sphinxcontrib.youtube",
    # "_sphinx_ext._sphinxcontrib_youtube",
    "_sphinx_ext._sphinx_ai_assistant",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None  # 'en' (English)

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

default_role = 'literal'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'sphinx_rtd_theme'
# html_theme = "furo"
html_theme = "pydata_sphinx_theme"  # scikit-learn like

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# https://pydata-sphinx-theme.readthedocs.io/en/v0.8.1/user_guide/configuring.html#configure-project-logo
html_logo = "_static/logos/scikit-plots-logo.svg"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "logos/scikit-plots-favicon.ico"

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {"index": "index.html"}

# If true, the reST sources are included in the HTML build as _sources/name.
html_copy_source = True

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Scikit-plotslearn'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Scikit-plotslearn.tex', 'Scikit-plots Learn',
     'scikit-plots community', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'scikit-plotslearn', 'Scikit-plots Learn',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'scikit-plotslearn', 'Scikit-plots Learn',
     author, 'scikit-plotslearn', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Sphinx-Issues configuration --

issues_github_path = "scikit-plots/scikit-plots"

# -- Sphinx-Tags configuration --

tags_create_tags = True
# tags_output_dir = "_tags"  # default: "_tags"
tags_overview_title = "Tags overview"  # default: "Tags overview"
tags_extension = ["rst"]  # default: ["rst"]
tags_intro_text = "Tags:"  # default: "Tags:"
tags_page_title = "My tags"  # default: "My tags"
tags_page_header = "With this tag"  # default: "With this tag"
tags_index_head = "Tags"  # default: "Tags"

tags_create_badges = True  # default: False
tags_badge_colors = {
    "t0": None,  # white-plain
    "model-type:*": "primary",  # seablue
    "model-workflow:*": "secondary",  # purple
    "plot-type:*": "success",  # green
    "level:*": "info",  # blue
    "event-handling:*": "warning",  # orange
    "domain:*": "danger",  # red
    "*": "light",  # Used as a default value # gray
    "purpose:*": "dark",  # black
}

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    "scikitplot": ("https://scikit-plots.github.io/dev/", (None, "https://scikit-plots.github.io/stable/")),
    # Build
    "python": (f"https://docs.python.org/{sys.version_info.major}/", None),
    "pip": ("https://pip.pypa.io/en/stable/", None),
    "meson-python": ("https://mesonbuild.com/meson-python/", None),
    "setuptools": ("https://setuptools.pypa.io/en/stable/", None),
    "packaging": ("https://packaging.python.org/en/latest/", None),
    "virtualenv": ("https://virtualenv.pypa.io/en/stable/", None),
    "IPython": ("https://ipython.readthedocs.io/en/stable/", None),
    "ipykernel": ("https://ipykernel.readthedocs.io/en/latest/", None),
    # Test
    "pytest": ("https://pytest.org/en/stable/", None),
    "tox": ("https://tox.wiki/en/stable/", None),
    # Docs
    'sphinx': ("https://www.sphinx-doc.org/en/master/", None),
    "pst": ("https://pydata-sphinx-theme.readthedocs.io/en/latest/", None),
    "numpydoc": ("https://numpydoc.readthedocs.io/en/latest/", None),
    # Data Manuplation
    "numpy": ("https://numpy.org/devdocs/", (None, "https://numpy.org/doc/stable/")),
    "scipy": ("https://scipy.github.io/devdocs/", (None, "https://docs.scipy.org/doc/scipy/")),
    "pandas": ("https://pandas.pydata.org/docs/dev/", (None, "https://pandas.pydata.org/pandas-docs/stable/")),
    # Visualization
    "cycler": ("https://matplotlib.org/cycler/", None),
    "matplotlib": ("https://matplotlib.org/devdocs/", (None, "https://matplotlib.org/stable/")),
    "astropy": ("https://docs.astropy.org/en/latest/", (None, "https://docs.astropy.org/en/stable/")),
    "seaborn": ("https://seaborn.pydata.org/", None),
    # ML
    "sklearn": ("https://scikit-learn.org/dev/", (None, "https://scikit-learn.org/stable/")),
    "statsmodels": ("https://www.statsmodels.org/stable/", None),
    # DL
    # 'keras': ('https://keras.io/api/', None),  # Add Keras API documentation
    "tensorflow": (
        "https://www.tensorflow.org/api_docs/python/",
        (
            None,
            "https://github.com/celik-muhammed/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
            "https://github.com/GPflow/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
            "https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tf2_py_objects.inv",
        ),
    ),
    "tensorflow_probability": (
        "https://www.tensorflow.org/probability/api_docs/python/",
        (
            None,
            "https://github.com/celik-muhammed/tensorflow-intersphinx/raw/master/tfp_py_objects.inv",
            "https://github.com/GPflow/tensorflow-intersphinx/raw/master/tfp_py_objects.inv",
            "https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tfp_py_objects.inv",
        ),
    ),
    "pytorch": (
        "https://pytorch.org/docs/stable/",
        (
            None,
            "https://github.com/pytorch/docs/raw/main/stable/objects.inv",
        ),
    ),
    "transformers": ("https://huggingface.co/docs/transformers/main/en/", None),
    "datasets": ("https://huggingface.co/docs/datasets/main/en/", None),
    # image
    "aggdraw": ("https://aggdraw.readthedocs.io/en/stable/", None),
    "pillow": ("https://pillow.readthedocs.io/en/stable/", None),
    "imageio": ("https://imageio.readthedocs.io/en/stable/", None),
    "skimage": ("https://scikit-image.org/docs/stable/", None),
    # Misc
    "joblib": ("https://joblib.readthedocs.io/en/latest/", None),
    "dateutil": ("https://dateutil.readthedocs.io/en/stable/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "skops": ("https://skops.readthedocs.io/en/stable/", None),
    "pluggy": ("https://pluggy.readthedocs.io/en/stable/", None),
    "flask": ("https://flask.palletsprojects.com/en/stable/", None),
}


# rst_prologue for docs text substitution
# will be included at the beginning of every source file that is read.
# Purpose:
# Injects reStructuredText substitution definitions into every RST source file.
# This lets you write |project| in any .rst file and have it replaced with the value.
# ✅ This affects RST parsing, and therefore any output format (HTML, PDF via LaTeX, etc.).
# rst_prolog = """
# .. |project| replace:: {project}
# .. include:: /global/roles.rst
# """.format(project=project)
#
# We use |scikit-learn| for classical ML, and |PyTorch| or |TensorFlow| for deep learning.
# To track experiments, `wandb`_ or `MLflow`_ can be used alongside `Optuna`_ for hyperparameter tuning.
# .. |PEP8| replace:: `PEP8 <https://www.python.org/dev/peps/pep-0008>`_
rst_prolog = f"""
.. |psf| replace:: Python Software Foundation
.. |full_version| replace:: {_full_version}

.. _PEP8: https://peps.python.org/pep-0008/
.. _Python: https://www.python.org/
.. _pip: https://pypi.org/project/pip/
.. _Cython: https://cython.org/
.. _setuptools: https://pypi.org/project/setuptools/
.. _PyPI: https://pypi.org/project
.. _dateutil: https://pypi.org/project/python-dateutil/
.. _distribute: https://pypi.org/project/distribute/
.. _pytest: https://docs.pytest.org/en/stable/
.. _pytest-cov: https://pytest-cov.readthedocs.io/en/latest/
.. _pytest-doctestplus: https://pypi.org/project/pytest-doctestplus/
.. _pytest-timeout: https://pypi.org/project/pytest-timeout/
.. _pytest-remotedata: https://pypi.org/project/pytest-remotedata/
.. _pytest-xdist: https://pypi.org/project/pytest-xdist/
.. _pytest-xvfb: https://pypi.org/project/pytest-xvfb/
.. _Ruff: https://docs.astral.sh/ruff/
.. _flake8: https://flake8.pycqa.org/
.. _black: https://black.readthedocs.io/
.. _venv: https://docs.python.org/3/library/venv.html
.. _Anaconda: https://conda.io/docs/
.. _conda: https://docs.conda.io/en/latest/
.. _mamba: https://mamba.readthedocs.io/en/latest/
.. _miniforge: https://github.com/conda-forge/miniforge
.. _NumPy: https://numpy.org/
.. _SciPy: https://scipy.org/
.. _pandas: https://pandas.pydata.org/
.. _Matplotlib: https://matplotlib.org/
.. _seaborn: https://seaborn.pydata.org/
.. _scikit-learn: https://scikit-learn.org/stable/
.. _xgboost: https://xgboost.readthedocs.io/
.. _lightgbm: https://lightgbm.readthedocs.io/
.. _catboost: https://catboost.ai/
.. _tensorflow: https://www.tensorflow.org/
.. _keras: https://keras.io/
.. _pytorch: https://pytorch.org/
.. _jax: https://jax.readthedocs.io/
.. _optuna: https://optuna.org/
.. _mlflow: https://mlflow.org/
.. _transformers: https://huggingface.co/docs/transformers/
.. _datasets: https://huggingface.co/docs/datasets/
.. _skorch: https://skorch.readthedocs.io/
.. _onnx: https://onnx.ai/
.. _wandb: https://wandb.ai/
.. _Weights & Biases: https://wandb.ai/
.. _pyparsing: https://pypi.org/project/pyparsing/
.. _pytz: https://pypi.org/project/pytz/
.. _six: https://pypi.org/project/six/
.. _easy_install: https://setuptools.readthedocs.io/en/latest/easy_install.html
.. _astropy: https://github.com/astropy/astropy
.. _astropy-tools: https://github.com/astropy/astropy-tools
.. _pytest-astropy: https://pypi.org/project/pytest-astropy/
.. _twine: https://packaging.python.org/key_projects/#twine
.. _signed tags: https://git-scm.com/book/en/v2/Git-Basics-Tagging#Signed-Tags
.. _generate_releaserst.xsh: https://raw.githubusercontent.com/sunpy/sunpy/main/tools/generate_releaserst.xsh
.. _numpydoc: https://numpydoc.readthedocs.io/en/latest/
.. _docutils: https://docutils.sourceforge.io/rst.html
.. _sphinx: https://pypi.org/project/Sphinx/
.. _sphinx-gallery: https://sphinx-gallery.readthedocs.io/en/latest/
.. _xarray: https://pypi.org/project/xarray/
.. _nbconvert: https://pypi.org/project/nbconvert/
.. _nbformat: https://pypi.org/project/nbformat/
.. _pikepdf: https://pypi.org/project/pikepdf/
.. _psutil: https://pypi.org/project/psutil/
.. _Inkscape: https://inkscape.org
.. _Ghostscript: https://ghostscript.com/

.. |PEP8| replace:: PEP8_
.. |Python| replace:: `Python`_
.. |pip| replace:: `pip`_
.. |Cython| replace:: `Cython`_
.. |setuptools| replace:: `setuptools`_
.. |PyPI| replace:: PyPI_
.. |dateutil| replace:: dateutil_
.. |distribute| replace:: distribute_
.. |pytest| replace:: pytest_
.. |pytest-cov| replace:: `pytest-cov`_
.. |pytest-doctestplus| replace:: `pytest-doctestplus`_
.. |pytest-timeout| replace:: `pytest-timeout`_
.. |pytest-remotedata| replace:: `pytest-remotedata`_
.. |pytest-xdist| replace:: `pytest-xdist`_
.. |pytest-xvfb| replace:: `pytest-xvfb`_
.. |Ruff| replace:: Ruff_
.. |flake8| replace:: flake8_
.. |black| replace:: black_
.. |venv| replace:: venv_
.. |Anaconda| replace:: Anaconda_
.. |conda| replace:: conda_
.. |mamba| replace:: mamba_
.. |miniforge| replace:: miniforge_
.. |NumPy| replace:: NumPy_
.. |SciPy| replace:: SciPy_
.. |pandas| replace:: pandas_
.. |Matplotlib| replace:: Matplotlib_
.. |seaborn| replace:: seaborn_
.. |scikit-learn| replace:: scikit-learn_
.. |xgboost| replace:: XGBoost_
.. |lightgbm| replace:: LightGBM_
.. |catboost| replace:: CatBoost_
.. |tensorflow| replace:: TensorFlow_
.. |keras| replace:: Keras_
.. |pytorch| replace:: PyTorch_
.. |jax| replace:: JAX_
.. |optuna| replace:: Optuna_
.. |mlflow| replace:: MLflow_
.. |transformers| replace:: 🤗 Transformers_
.. |datasets| replace:: 🤗 Datasets_
.. |skorch| replace:: skorch_
.. |onnx| replace:: ONNX_
.. |wandb| replace:: `Weights & Biases`_
.. |pyparsing| replace:: pyparsing_
.. |pytz| replace:: pytz_
.. |six| replace:: six_
.. |easy_install| replace:: easy_install_
.. |astropy| replace:: astropy_
.. |astropy-tools| replace:: astropy-tools_
.. |pytest-astropy| replace:: pytest-astropy_
.. |twine| replace:: twine_
.. |signed tags| replace:: `signed tags`_
.. |generate_releaserst.xsh| replace:: `generate_releaserst.xsh`_
.. |numpydoc| replace:: numpydoc_
.. |docutils| replace:: docutils_
.. |sphinx| replace:: sphinx_
.. |sphinx-gallery| replace:: sphinx-gallery_
.. |xarray| replace:: xarray_
.. |nbconvert| replace:: nbconvert_
.. |nbformat| replace:: nbformat_
.. |pikepdf| replace:: pikepdf_
.. |psutil| replace:: psutil_
.. |Inkscape| replace:: Inkscape_
.. |Ghostscript| replace:: Ghostscript_

.. _minimum_numpy_version: 1.20
.. |minimum_numpy_version| replace:: minimum_numpy_version_

.. _astropy-dev mailing list: https://github.com/astropy/astropy
.. |astropy-dev mailing list| replace:: `astropy-dev mailing list`_

.. |emoji| unicode:: U+1F680
   :trim:
"""

##########################################################################
## Extension: scikitplot/_externals/_sphinx_ext/_sphinx_ai_assistant options
## Learn project — Run 33 alignment, explicit/privacy-first/profile-based
##########################################################################

# Base URL used by generated Markdown/llms.txt links and page-level metadata.
html_baseurl = "https://scikit-plots-learn.readthedocs.io/en/latest"  # Learn docs

# ---------------------------------------------------------------------------
# Core extension + generated context
# ---------------------------------------------------------------------------
ai_assistant_enabled = True
ai_assistant_position = "sidebar"

# Runtime/live-DOM content root and build-time fallback selectors.
ai_assistant_content_selector = "article.bd-article"
ai_assistant_content_selectors = [
    "article.bd-article",      # PyData Sphinx Theme
    'article[role="main"]',    # Furo
    'div[role="main"]',        # RTD / older themes
    "div.document",            # Classic / Alabaster
    "div.body",
    "main",
    "article",
]

# Build-time Markdown companions and llms.txt.
ai_assistant_generate_markdown = True
ai_assistant_markdown_exclude_patterns = [
    "genindex",
    "search",
    "py-modindex",
    "_sources",
    "_static",
]
ai_assistant_strip_tags = ["script", "style", "nav", "footer"]
ai_assistant_max_workers = 1  # conservative for large docs builds

ai_assistant_generate_llms_txt = True
ai_assistant_base_url = ""  # inherit html_baseurl
ai_assistant_llms_txt_max_entries = None
# Keep the index compact; page.md files already contain the full page text.
ai_assistant_llms_txt_full_content = False
ai_assistant_llms_txt_format = "structured"
ai_assistant_llms_txt_summary = None
ai_assistant_llms_txt_sections = None

# Copy uses the live browser DOM by default; readers may switch to static page.md.
ai_assistant_copy_mode = "browser"  # "browser" | "static"
ai_assistant_copy_mode_toggle = True

# Fail-soft remains appropriate for optional docs features. Set True in CI when
# missing Markdown-generation dependencies should fail the documentation build.
ai_assistant_strict = False

# Optional prompt/context author hooks. Keep raw-image injection off by default.
ai_assistant_intention = None
ai_assistant_custom_context = None
ai_assistant_custom_prompt_prefix = None
ai_assistant_include_raw_image = False

# ---------------------------------------------------------------------------
# Top-level feature switches
# ---------------------------------------------------------------------------
ai_assistant_features = {
    "markdown_export": True,
    "view_markdown": True,
    "ai_chat": True,
    "mcp_integration": True,
    "theme_toggle": True,
    "pdf_export": True,
    "ai_panel": True,
}

# PDF URL/Print chooser.
ai_assistant_pdf_url_mode_toggle = True
ai_assistant_pdf_export_url = f"{html_baseurl}"

# ---------------------------------------------------------------------------
# Standalone AI search bar
# ---------------------------------------------------------------------------
ai_assistant_search_bar = True
ai_assistant_search_bar_mini = False
ai_assistant_search_bar_selector = ".bd-sidebar-primary"
ai_assistant_search_bar_position = "top"
ai_assistant_panel_search_placeholder = "Ask AI about these docs…"

# ---------------------------------------------------------------------------
# Web/deep-link providers
# ---------------------------------------------------------------------------
ai_assistant_providers = {
    # --- Tier 1: enabled by default ----------------------------------------
    "chatgpt": {
        "enabled": True,
        "label": "Ask ChatGPT",
        "description": "Ask OpenAI ChatGPT about this page",
        "icon": "chatgpt.svg",
        "url_template": "https://chatgpt.com/?q={prompt}",
        "prompt_template": (
            "Hi! Please read this documentation page: {url}\n\n"  # + "{content}"
            "I have questions about it."
        ),
        "model": "gpt-4o",
        "type": "web",
    },
    "claude": {
        # Enabled: users can click "Ask Claude" without any setup.
        "enabled": True,
        # Button label shown inside the AI-assistant panel.
        "label": "Ask Claude",
        # Tooltip / screen-reader accessible description.
        "description": "Ask Anthropic Claude about this page",
        # SVG icon filename in _static/.  Falls back to a base64 data URI
        # from ``_static/_PROVIDER_META`` if the file is absent on disk.
        "icon": "claude.svg",
        # URL template: {prompt} is substituted with the URL-encoded prompt.
        # Claude's ?q= parameter accepts the full prompt string directly.
        "url_template": "https://claude.ai/new?q={prompt}",
        # Prompt template: {url} → absolute URL of the page's .md companion;
        # {content} → raw Markdown text (can be large for long pages).
        # Using {url} keeps prompts short; Claude fetches and reads the page.
        "prompt_template": (
            "Hi! Please read this documentation page: {url}\n\n"  # + "{content}"
            "I have questions about it."
        ),
        # Model identifier.  Forwarded to the widget for future API-mode use.
        "model": "claude-sonnet-4-6",
        # "web" opens a browser tab; no API key is required from the user.
        "type": "web",
    },
    "gemini": {
        "enabled": True,
        "label": "Ask Gemini",
        "description": "Ask Google Gemini about this page",
        "icon": "gemini.svg",
        "url_template": "https://gemini.google.com/app?q={prompt}",
        "prompt_template": (
            "Hi! Please review this documentation content: {url}\n\n"  # + "{content}"
            "I have questions about it."
        ),
        "model": "gemini-2.5-flash",
        "type": "web",
    },
}

# ---------------------------------------------------------------------------
# Floating AI panel — UI, state, reasoning/effort, and request behavior
# ---------------------------------------------------------------------------
ai_assistant_panel_title = "AI Assistant"
ai_assistant_panel_placeholder = "Ask a question about this page…"
ai_assistant_panel_api_enabled = True
ai_assistant_panel_quick_questions = [
    "What does this page cover?",
    "Show me a quick usage example.",
    "What are the key parameters?",
]
ai_assistant_panel_page_help = True
ai_assistant_panel_speak_banner = True
ai_assistant_panel_trigger_label = "Ask AI"
ai_assistant_panel_start_minimized = True
ai_assistant_panel_trigger_toggle = True
ai_assistant_panel_persist = True
ai_assistant_panel_shortcut = "Alt+Shift+A"

# Reasoning/effort is capability-gated. False means the UI may expose the
# controls/editor, but unsupported wire parameters are never guessed/sent.
ai_assistant_panel_reasoning = False
ai_assistant_panel_effort_levels = []      # built-in/provider-aware presets
ai_assistant_panel_effort_default = ""
ai_assistant_panel_model_editing = True
ai_assistant_panel_stub_models = True
ai_assistant_panel_injection_notice = True
ai_assistant_panel_inline_model_picker = True
ai_assistant_panel_api_streaming = True

# ---------------------------------------------------------------------------
# Proxy authority — one public browser-facing base, secrets stay server-side
# ---------------------------------------------------------------------------
# AI_PROXY_BASE is canonical. PROXY_BASE_URL remains a compatibility fallback.
# Never put HF_TOKEN/API keys/bearer credentials in this file: conf.py values
# are serialized into public documentation HTML when consumed by the extension.
_AI_PROXY_BASE: str = (
    os.environ.get("AI_PROXY_BASE")
    or os.environ.get("PROXY_BASE_URL")
    or "https://scikit-plots-ai.hf.space"
).rstrip("/")

ai_assistant_panel_api_models = [
    # ── Paid-tier entries (commented out — require deployed proxies) ──────
    # Uncomment once you have a running proxy with the relevant API key.
    # {
    #     "id":          "claude-sonnet-4-6",
    #     "label":       "Claude Sonnet 4.6",
    #     "provider":    "anthropic",
    #     "model":       "claude-sonnet-4-20250514",
    #     "endpoint":    "/_proxy/anthropic",   # proxy injects ANTHROPIC_API_KEY
    #     "info_url":    "https://www.anthropic.com/claude",
    #     "description": "Anthropic sonnet flagship — strong reasoning, long context.",
    # },
    # {
    #     "id":          "gpt-4o",
    #     "label":       "GPT-4o",
    #     "provider":    "openai",
    #     "model":       "gpt-4o",
    #     "endpoint":    "/_proxy/openai",      # proxy injects OPENAI_API_KEY
    #     "info_url":    "https://openai.com/index/hello-gpt-4o/",
    #     "description": "Openai chatgpt.",
    # },
    # {
    #     "id":          "gemini-2.5-flash",
    #     "label":       "Gemini 2.5 Flash",
    #     "provider":    "google",
    #     "model":       "gemini-2.5-flash",
    #     "endpoint":    "/_proxy/gemini",      # proxy injects GEMINI_API_KEY
    #     "info_url":    "https://ai.google.dev/gemini-api/docs/models",
    #     "description": "Google gemini.",
    # },
    #
    # ── HuggingFace GPT-OSS-20B (upstream OpenAI release) ────────────────
    # Same proxy, model field selects the upstream checkpoint.
    # Proxy MUST inject a valid HuggingFace API token server-side:
    #     Authorization: Bearer ${HF_TOKEN}
    # NEVER embed the token in this conf.py file.
    # Model card: https://huggingface.co/openai/gpt-oss-20b
    {
        "id":          "gpt-oss-20b-hf",
        "label":       "GPT-OSS 20B (OpenAI/HuggingFace)",
        "provider":    "huggingface",
        "model":       "openai/gpt-oss-20b",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/openai/gpt-oss-20b",
        "description": (
            "OpenAI open-source 20B via HuggingFace Inference API — "
            "OpenAI-compat /v1/chat/completions, SSE streaming enabled."
        ),
    },
    {
        "default":     True,
        "id":          "Qwen2.5-Coder-7B-Instruct-hf",
        "label":       "Qwen2.5-Coder-7B-Instruct (Qwen/HuggingFace)",
        "provider":    "huggingface",
        "model":       "Qwen/Qwen2.5-Coder-7B-Instruct",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
        "description": (
            "Qwen2.5-Coder is the latest series of Code-Specific Qwen large language models (formerly known as CodeQwen). "
            "For more:https://github.com/QwenLM"
        ),
    },
    {
        "id":          "Qwen2.5-Coder-32B-Instruct-hf",
        "label":       "Qwen2.5-Coder-32B-Instruct (Qwen/HuggingFace)",
        "provider":    "huggingface",
        "model":       "Qwen/Qwen2.5-Coder-32B-Instruct",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
        "description": (
            "Qwen2.5-Coder is the latest series of Code-Specific Qwen large language models (formerly known as CodeQwen). "
            "For more:https://github.com/QwenLM"
        ),
    },
    # ── scikit-plots fine-tuned GPT-OSS-20B ──────────────────────────────
    # Fine-tuned for scikit-plots documentation Q&A.
    # Model card: https://huggingface.co/scikit-plots/gpt-oss-20b
    #
    # IMPORTANT — endpoint resolution (environment-aware):
    #   AI_PROXY_BASE is the single knob that selects which free proxy to use.
    #   Set it as an environment variable or CI/CD secret:
    #
    #   Local development (dev_proxy.py on port 8787):
    #       export AI_PROXY_BASE=http://localhost:8787
    #
    #   Staging / CI (HuggingFace Space — Option A, always free):
    #       export AI_PROXY_BASE=https://scikit-plots-ai.hf.space
    #
    #   Production (Cloudflare Worker — Option B, 100 000 req/day free):
    #       export AI_PROXY_BASE=https://hf-proxy.<your-subdomain>.workers.dev
    #
    # The _PROXY_BASE import at the top of this block reads the env var with
    # a sensible fallback so local builds work without any shell setup, and
    # CI/CD secrets transparently select the production proxy.
    #
    # SECURITY: API tokens (HF_TOKEN, ANTHROPIC_API_KEY, …) MUST NEVER appear
    # here.  They live only in the proxy's environment secret store.
    {
        "id":          "gpt-oss-20b-skplt",
        "label":       "GPT-OSS 20B (scikit-plots/HuggingFace)",
        "provider":    "huggingface",
        "model":       "scikit-plots/gpt-oss-20b",
        # Resolved at build time from AI_PROXY_BASE; see comment above.
        # Replace with a literal URL once your proxy is deployed, e.g.:
        #   "endpoint": "https://scikit-plots-ai.hf.space/v1/chat/completions",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/scikit-plots/gpt-oss-20b",
        "description": (
            "(future) scikit-plots fine-tune of GPT-OSS-20B — trained on the full "
            "scikit-plots documentation corpus for higher answer accuracy."
        ),
    },
    {
        "id":          "Qwen2.5-Coder-7B-Instruct-skplt",
        "label":       "Qwen2.5-Coder-7B-Instruct (scikit-plots/HuggingFace)",
        "provider":    "huggingface",
        "model":       "scikit-plots/Qwen2.5-Coder-7B-Instruct",
        # Resolved at build time from AI_PROXY_BASE; see comment above.
        # Replace with a literal URL once your proxy is deployed, e.g.:
        #   "endpoint": "https://scikit-plots-ai.hf.space/v1/chat/completions",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/scikit-plots/Qwen2.5-Coder-7B-Instruct",
        "description": (
            "(future) scikit-plots fine-tune of Qwen2.5-Coder-7B-Instruct — trained on the full "
            "scikit-plots documentation corpus for higher answer accuracy."
        ),
    },
    {
        "id":          "Qwen2.5-Coder-32B-Instruct-skplt",
        "label":       "Qwen2.5-Coder-32B-Instruct (scikit-plots/HuggingFace)",
        "provider":    "huggingface",
        "model":       "scikit-plots/Qwen2.5-Coder-32B-Instruct",
        # Resolved at build time from AI_PROXY_BASE; see comment above.
        # Replace with a literal URL once your proxy is deployed, e.g.:
        #   "endpoint": "https://scikit-plots-ai.hf.space/v1/chat/completions",
        "endpoint":    _AI_PROXY_BASE + "/v1/chat/completions",
        "info_url":    "https://huggingface.co/scikit-plots/Qwen2.5-Coder-32B-Instruct",
        "description": (
            "(future) scikit-plots fine-tune of Qwen2.5-Coder-32B-Instruct — trained on the full "
            "scikit-plots documentation corpus for higher answer accuracy."
        ),
    },
]

# ---------------------------------------------------------------------------
# Usage / policy / share / project-link sheets
# ---------------------------------------------------------------------------
ai_assistant_panel_usage_policy = True
ai_assistant_panel_usage_policy_title = "Usage Policy"
ai_assistant_panel_usage_policy_html = ""  # built-in safe default

ai_assistant_panel_terms = True
ai_assistant_panel_terms_title = "Terms of Service"
ai_assistant_panel_terms_link_text = "Terms of Service"
ai_assistant_panel_terms_html = ""

ai_assistant_panel_share = True
ai_assistant_panel_share_label = "Share"
ai_assistant_panel_share_targets = []  # built-in targets

ai_assistant_panel_links = True
ai_assistant_panel_links_title = "Project Links"
ai_assistant_panel_links_html = ""

ai_assistant_panel_source = True
ai_assistant_panel_source_url = "https://github.com/scikit-plots/scikit-plots"
ai_assistant_panel_source_label = "GitHub Source"
ai_assistant_panel_source_desc = "Browse, contribute, report issues, and review the scikit-plots source."
ai_assistant_panel_source_btn_label = "Source"

ai_assistant_panel_site = True
ai_assistant_panel_site_url = f"{html_baseurl}"
ai_assistant_panel_site_label = "Documentation Site"
ai_assistant_panel_site_desc = "Explore the scikit-plots API reference and user guide."
ai_assistant_panel_site_btn_label = "Website"

# Dataset/contribution resource cards. The active endpoint is derived from the
# endpoint profile unless explicitly overridden.
ai_assistant_panel_dataset_repo = "scikit-plots/ai-assistant-contributions"
ai_assistant_panel_hf_space_url = ""
ai_assistant_panel_hf_space_label = "HuggingFace Space"
ai_assistant_panel_hf_dataset_url = ""
ai_assistant_panel_hf_dataset_label = "HuggingFace Dataset"
ai_assistant_panel_hf_endpoint_url = ""
ai_assistant_panel_hf_endpoint_label = "Active Endpoint"

ai_assistant_panel_hamburger = True

# ---------------------------------------------------------------------------
# Feedback / telemetry / privacy
# ---------------------------------------------------------------------------
# Local rating UI is always usable. Network telemetry remains separately
# permission-gated by the runtime; logging stays off by default.
ai_assistant_panel_feedback = True
ai_assistant_panel_feedback_question = "Was this helpful?"
ai_assistant_panel_feedback_options = []   # built-in adaptive gradient
ai_assistant_panel_feedback_scale = "auto"
ai_assistant_panel_feedback_placeholder = ""
ai_assistant_panel_feedback_submit = "Send feedback"
ai_assistant_panel_feedback_thanks = "Thanks for your feedback!"
ai_assistant_panel_feedback_log = False

ai_assistant_panel_privacy_title = "Privacy & Responsibility"
ai_assistant_panel_privacy_link_text = "Privacy & Responsibility"
ai_assistant_panel_privacy_html = ""       # built-in structured privacy copy

# Browser-entered bearer credentials and ambient cookies remain OFF. Production
# authorization belongs on the proxy/service, not in static docs or Web Storage.
ai_assistant_allow_runtime_tokens = False
ai_assistant_allow_credentialed_fetch = False

# ---------------------------------------------------------------------------
# Separate-origin isolation — explicit safe defaults
# ---------------------------------------------------------------------------
# Leave origin empty for current same-origin mode. For strict deployments set a
# dedicated HTTPS origin and configure the proxy CORS allow-list for that origin.
ai_assistant_isolation_origin = ""
ai_assistant_isolation_frame_path = "/ai-assistant-isolated.html"
ai_assistant_isolation_context_max_chars = 200_000
ai_assistant_isolation_parent_origins = []  # derive from html_baseurl when enabled
ai_assistant_isolation_allow_microphone = False

# ---------------------------------------------------------------------------
# Endpoint profile registry — preferred modern configuration
# ---------------------------------------------------------------------------
# One browser-visible BASE URL feeds the built-in routes:
#   chat     -> /v1/chat/completions
#   share    -> /v1/share
#   feedback -> /v1/feedback
#   training -> /v1/contribute
# No build-time tokens belong in this profile. The service authenticates
# upstream/server-side writes using its own secret store.
ai_assistant_global_share_ttl_days = 30
ai_assistant_endpoint_profiles = {
    "default": {
        "label": "Default Proxy",
        "base": _AI_PROXY_BASE,
        "datasetRepo": "scikit-plots/ai-assistant-contributions",
        "ttlDays": 30,
    },
}
ai_assistant_endpoint_default_profile = "default"

# Legacy flat endpoint/token keys are intentionally NOT set when explicit
# profiles are present. Explicit profiles take precedence, and static token
# config is deprecated/ignored by the latest extension.

ai_assistant_mcp_tools = {
    "vscode": {
        # Enable once your MCP server is deployed at a stable HTTPS URL.
        "enabled": False,  # set True to show the VS Code button
        # Widget renders a VS Code "Install Extension" style deep-link that
        # opens VS Code and installs / activates the MCP server.
        "type": "vscode",
        "label": "Connect to VS Code",
        "description": "Install your MCP server directly into VS Code.",
        "icon": "vscode.svg",
        # Unique identifier shown in the VS Code MCP server sidebar entry.
        "server_name": "your-docs-mcp-server",
        # SSE endpoint URL of your deployed MCP server.
        # Use https:// for production; http://localhost is accepted locally.
        "server_url": "https://your-docs-mcp-server/sse",
        # Transport protocol:
        #   "sse"   — HTTP Server-Sent Events (standard for remote servers)
        #   "stdio" — standard I/O pipes (local command-line MCP servers)
        "transport": "sse",
    },

    "claude_desktop": {
        # Enable once you have a deployable mcpb:// bundle or config ZIP.
        "enabled": False,  # set True to show the Claude button
        # Widget renders a Claude Desktop "mcpb://" deep-link button that
        # opens Claude Desktop and installs the MCP server configuration.
        "type": "claude_desktop",
        "label": "Connect to Claude",
        "description": "Download and run the Claude MCP bundle.",
        "icon": "claude.svg",
        # mcpb:// URL (Claude Desktop's custom protocol for MCP bundles), or
        # an https:// URL pointing to a downloadable MCP config ZIP archive.
        "mcpb_url": "https://docs.example.com/_static/your-mcpb-config.zip",
    },

    "cursor": {
        # Enable once your MCP server is deployed at a stable HTTPS URL.
        "enabled": False,
        # Widget renders a Cursor IDE "Install MCP Server" style deep-link
        # that opens Cursor and activates the MCP server integration.
        "type": "cursor",
        "label": "Connect to Cursor",
        "description": "Connect the MCP server to Cursor IDE.",
        "icon": "cursor.svg",
        # Unique identifier shown in the Cursor MCP server sidebar entry.
        "server_name": "your-docs-mcp-server",
        # SSE endpoint URL of your deployed MCP server.
        # Use https:// for production; http://localhost is accepted locally.
        "server_url": "https://your-docs-mcp-server/sse",
        # Transport protocol:
        #   "sse"   — HTTP Server-Sent Events (standard for remote servers)
        #   "stdio" — standard I/O pipes (local command-line MCP servers)
        "transport": "sse",
    },
}
